-- v1 MVP tables: durable review state, PR queue, configured repos, settings
-- Run against your Supabase project after 20260613000000_memory_tables.sql
-- ============================================================
-- reviews
-- Replaces the in-process review-cache.ts Map.
-- Persists review state across Railway restarts and replicas.
-- ============================================================
create table if not exists reviews (
  id text primary key, -- UUID generated by the start route
  pr_url text not null,
  pr_metadata jsonb not null default '{}', -- { owner, repo, number, title, head, base, author }
  mode text not null default 'full', -- 'full' | 'quick'
  status text not null default 'RUNNING', -- RUNNING | COMPLETE | ERROR
  result jsonb, -- serialized PRReview (set when COMPLETE)
  submission jsonb, -- serialized ReviewSubmission (set on finalize)
  error_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists reviews_status_idx on reviews (status);

create index if not exists reviews_created_at_idx on reviews (created_at desc);

-- ============================================================
-- tracked_prs
-- The PR review queue: one row per open PR per configured repo.
-- ============================================================
create table if not exists tracked_prs (
  id uuid primary key default gen_random_uuid(),
  owner text not null,
  repo text not null,
  pr_number int not null,
  pr_url text not null,
  pr_title text,
  pr_author text,
  pr_opened_at timestamptz,
  pr_closed_at timestamptz,
  -- OPEN: awaiting review
  -- IN_REVIEW: review currently running
  -- REVIEWED: review submitted; new commits flip back to OPEN
  -- CLOSED: PR merged or closed on GitHub
  status text not null default 'OPEN',
  updated_since_review boolean not null default false, -- true when synchronize event arrives after REVIEWED
  last_review_id text references reviews (id) on delete set null,
  review_count int not null default 0,
  source text not null default 'MANUAL', -- MANUAL | WEBHOOK
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (owner, repo, pr_number)
);

create index if not exists tracked_prs_status_idx on tracked_prs (status);

create index if not exists tracked_prs_repo_idx on tracked_prs (owner, repo);

-- ============================================================
-- configured_repos
-- Repos the admin has registered for PR review tracking.
-- Each repo can optionally have a GitHub webhook secret.
-- ============================================================
create table if not exists configured_repos (
  id uuid primary key default gen_random_uuid(),
  owner text not null,
  name text not null,
  webhook_secret text, -- set when webhook is installed; null = no webhook
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (owner, name)
);

-- ============================================================
-- settings
-- Key/value store for in-app configuration.
-- e.g. key='conventions', value='## Naming\n...' (markdown)
-- ============================================================
create table if not exists settings (
  key text primary key,
  value jsonb not null default '{}',
  updated_at timestamptz not null default now()
);

-- ============================================================
-- updated_at triggers
-- ============================================================
create or replace function set_updated_at () returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger reviews_updated_at
before update on reviews for each row
execute function set_updated_at ();

create trigger tracked_prs_updated_at
before update on tracked_prs for each row
execute function set_updated_at ();

create trigger configured_repos_updated_at
before update on configured_repos for each row
execute function set_updated_at ();

create trigger settings_updated_at
before update on settings for each row
execute function set_updated_at ();

-- ============================================================
-- Row-level security
-- ============================================================
alter table reviews enable row level security;

alter table tracked_prs enable row level security;

alter table configured_repos enable row level security;

alter table settings enable row level security;

-- Authenticated users can read everything
create policy "authenticated can read reviews" on reviews for
select
  to authenticated using (true);

create policy "authenticated can read tracked_prs" on tracked_prs for
select
  to authenticated using (true);

create policy "authenticated can read configured_repos" on configured_repos for
select
  to authenticated using (true);

create policy "authenticated can read settings" on settings for
select
  to authenticated using (true);

-- Authenticated users can manage configured_repos and settings (admin actions)
create policy "authenticated can insert configured_repos" on configured_repos for insert to authenticated
with
  check (true);

create policy "authenticated can update configured_repos" on configured_repos
for update
  to authenticated using (true);

create policy "authenticated can delete configured_repos" on configured_repos for delete to authenticated using (true);

create policy "authenticated can upsert settings" on settings for insert to authenticated
with
  check (true);

create policy "authenticated can update settings" on settings
for update
  to authenticated using (true);

-- Service role handles reviews and tracked_prs writes (server-side only, bypasses RLS)
